#!/bin/sh

# Uses pysilfont tools

psffixffglifs -p checkfix=fix source/masters/HispaMaster-ExtraLight.ufo -l logs/fixffXL.log
psffixffglifs -p checkfix=fix source/masters/HispaMaster-Medium.ufo -l logs/fixffM.log
psffixffglifs -p checkfix=fix source/masters/HispaMaster-Black.ufo -l logs/fixffBL.log

psfsetpsnames -i source/glyph_data.csv source/masters/HispaMaster-Medium.ufo -l logs/psnames.log
psfsetglyphorder --header sort_final,sort_g --field public.glyphOrder,com.schriftgestaltung.glyphOrder -i source/glyph_data.csv source/masters/HispaMaster-Medium.ufo -l logs/sortorder.log

psfsyncmasters source/HispaRoman.designspace -l logs/sync.log
